name: Rerun Failed Workflows

on:
  workflow_dispatch: # Allows you to manually trigger this workflow from the GitHub Actions tab

jobs:
  rerun_failed_workflows:
    runs-on: ubuntu-latest

    steps:
    - name: List All Workflows
      id: list_workflows
      run: |
        # Get all workflows, filter by those with 'failure' conclusion
        curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{ github.repository }}/actions/runs?status=failure > failed_workflows.json

    - name: Extract Failed Workflow Run IDs
      id: extract_ids
      run: |
        # Extract failed workflow run IDs from the JSON response
        cat failed_workflows.json | jq '.workflow_runs[].id' > failed_workflow_ids.txt

    - name: Rerun Failed Workflows
      run: |
        # Iterate over the failed workflow IDs and rerun them using GitHub API
        for id in $(cat failed_workflow_ids.txt); do
          echo "Rerunning workflow run ID: $id"
          curl -X POST \
          -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/runs/$id/rerun
        done
